import { Mulish } from 'next/font/google';
import Container from '@/components/Container';
import Footer from '@/layout/Footer';
import Header from '@/layout/Header';
import type { Metadata } from 'next';
import './globals.css';

const mulish = Mulish({
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body
      className={mulish.className}
      suppressHydrationWarning
    >
      <div className="grid grid-rows-layout grid-cols-[100%] [grid-template-areas:'header''main''footer'] min-h-screen">
        <Header />
        <main className="[grid-area:main] pt-11 pb-20">
          <Container>{children}</Container>
        </main>
        <Footer />
      </div>
    </body>
  </html>
);

export default RootLayout;
